<<<<<<< HEAD
easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Vm
        - App\Entity\Backup
        - App\Entity\Plan
=======
#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
>>>>>>> e815e9b692a3ec39450884aad7137962fd31920f
